// All shop items defined here
const ITEMS = {
  // ── TOOLS ──────────────────────────────────────────────────────────────
  fishing_rod: {
    itemId: 'fishing_rod',
    name: 'Fishing Rod',
    emoji: '🎣',
    description: 'Required to go fishing. Catch fish and sell them!',
    category: 'tool',
    rarity: 'common',
    buyPrice: 2000,
    sellPrice: 800,
    buyable: true,
    sellable: true,
    usable: false,
  },
  rifle: {
    itemId: 'rifle',
    name: 'Rifle',
    emoji: '🔫',
    description: 'Required to go hunting. Hunt animals for money!',
    category: 'tool',
    rarity: 'common',
    buyPrice: 5000,
    sellPrice: 2000,
    buyable: true,
    sellable: true,
    usable: false,
  },
  shovel: {
    itemId: 'shovel',
    name: 'Shovel',
    emoji: '⛏️',
    description: 'Required to dig for buried treasure and materials!',
    category: 'tool',
    rarity: 'common',
    buyPrice: 1500,
    sellPrice: 600,
    buyable: true,
    sellable: true,
    usable: false,
  },
  axe: {
    itemId: 'axe',
    name: 'Axe',
    emoji: '🪓',
    description: 'Required to chop wood for crafting!',
    category: 'tool',
    rarity: 'common',
    buyPrice: 3000,
    sellPrice: 1200,
    buyable: true,
    sellable: true,
    usable: false,
  },
  telescope: {
    itemId: 'telescope',
    name: 'Telescope',
    emoji: '🔭',
    description: 'Reveals the current market trend for any asset. Use once per day.',
    category: 'tool',
    rarity: 'rare',
    buyPrice: 10000,
    sellPrice: 4000,
    buyable: true,
    sellable: true,
    usable: true,
    effect: 'market_peek',
  },
  test_kit: {
    itemId: 'test_kit',
    name: 'Test Kit',
    emoji: '🧪',
    description: 'Reveals your crop yield before harvesting.',
    category: 'tool',
    rarity: 'uncommon',
    buyPrice: 8000,
    sellPrice: 3000,
    buyable: true,
    sellable: true,
    usable: true,
    effect: 'crop_peek',
  },

  // ── BOOSTS ─────────────────────────────────────────────────────────────
  xp_booster: {
    itemId: 'xp_booster',
    name: 'XP Booster',
    emoji: '💊',
    description: '2x XP gain for 1 hour!',
    category: 'boost',
    rarity: 'uncommon',
    buyPrice: 5000,
    sellPrice: 1500,
    buyable: true,
    sellable: true,
    usable: true,
    effect: 'xp_boost',
    effectValue: 2,
    effectDuration: 60 * 60 * 1000,
  },
  energy_drink: {
    itemId: 'energy_drink',
    name: 'Energy Drink',
    emoji: '☕',
    description: 'Halves your work cooldown for 3 uses!',
    category: 'boost',
    rarity: 'common',
    buyPrice: 1000,
    sellPrice: 300,
    buyable: true,
    sellable: true,
    usable: true,
    effect: 'work_cooldown',
    effectValue: 0.5,
    effectDuration: 3,
  },
  mega_fertilizer: {
    itemId: 'mega_fertilizer',
    name: 'Mega Fertilizer',
    emoji: '🌿',
    description: '3x farm yield on next harvest!',
    category: 'boost',
    rarity: 'uncommon',
    buyPrice: 8000,
    sellPrice: 3000,
    buyable: true,
    sellable: true,
    usable: true,
    effect: 'farm_boost',
    effectValue: 3,
  },
  sharpshooter: {
    itemId: 'sharpshooter',
    name: 'Sharpshooter',
    emoji: '🎯',
    description: '2x hunting rewards for 5 uses!',
    category: 'boost',
    rarity: 'uncommon',
    buyPrice: 6000,
    sellPrice: 2000,
    buyable: true,
    sellable: true,
    usable: true,
    effect: 'hunt_boost',
    effectValue: 2,
    effectDuration: 5,
  },
  pro_bait: {
    itemId: 'pro_bait',
    name: 'Pro Bait',
    emoji: '🪱',
    description: '2x fishing rewards for 5 uses!',
    category: 'boost',
    rarity: 'common',
    buyPrice: 4000,
    sellPrice: 1500,
    buyable: true,
    sellable: true,
    usable: true,
    effect: 'fish_boost',
    effectValue: 2,
    effectDuration: 5,
  },
  gold_magnet: {
    itemId: 'gold_magnet',
    name: 'Gold Magnet',
    emoji: '🧲',
    description: '+25% work pay for 2 hours!',
    category: 'boost',
    rarity: 'rare',
    buyPrice: 12000,
    sellPrice: 4500,
    buyable: true,
    sellable: true,
    usable: true,
    effect: 'work_boost',
    effectValue: 1.25,
    effectDuration: 2 * 60 * 60 * 1000,
  },
  casino_chip: {
    itemId: 'casino_chip',
    name: 'Casino Chip',
    emoji: '🎰',
    description: '1 free casino spin — no bet required!',
    category: 'boost',
    rarity: 'rare',
    buyPrice: 20000,
    sellPrice: 7000,
    buyable: true,
    sellable: true,
    usable: true,
    effect: 'free_spin',
  },
  tax_shield: {
    itemId: 'tax_shield',
    name: 'Tax Shield',
    emoji: '💸',
    description: 'No tax on your next gift transfer!',
    category: 'boost',
    rarity: 'uncommon',
    buyPrice: 25000,
    sellPrice: 8000,
    buyable: true,
    sellable: true,
    usable: true,
    effect: 'no_tax',
  },
  vip_card: {
    itemId: 'vip_card',
    name: 'VIP Card',
    emoji: '🪪',
    description: 'Skip all cooldowns once!',
    category: 'boost',
    rarity: 'epic',
    buyPrice: 50000,
    sellPrice: 20000,
    buyable: true,
    sellable: true,
    usable: true,
    effect: 'skip_cooldowns',
  },
  time_warp: {
    itemId: 'time_warp',
    name: 'Time Warp',
    emoji: '⏰',
    description: 'Reset ALL your cooldowns instantly!',
    category: 'special',
    rarity: 'legendary',
    buyPrice: 200000,
    sellPrice: 80000,
    buyable: false,
    sellable: true,
    usable: true,
    effect: 'reset_all_cooldowns',
  },

  // ── COLLECTIBLES ───────────────────────────────────────────────────────
  stone: {
    itemId: 'stone',
    name: 'Stone',
    emoji: '🪨',
    description: 'A plain rock. Worth something to the right buyer.',
    category: 'collectible',
    rarity: 'common',
    buyPrice: 10,
    sellPrice: 5,
    buyable: true,
    sellable: true,
  },
  copper: {
    itemId: 'copper',
    name: 'Copper',
    emoji: '🥉',
    description: 'Raw copper ore. Used in crafting.',
    category: 'collectible',
    rarity: 'common',
    buyPrice: 100,
    sellPrice: 80,
    buyable: true,
    sellable: true,
  },
  silver_bar: {
    itemId: 'silver_bar',
    name: 'Silver Bar',
    emoji: '🥈',
    description: 'A shiny silver bar.',
    category: 'collectible',
    rarity: 'uncommon',
    buyPrice: 500,
    sellPrice: 450,
    buyable: true,
    sellable: true,
  },
  gold_bar: {
    itemId: 'gold_bar',
    name: 'Gold Bar',
    emoji: '🥇',
    description: 'Pure gold. Very valuable.',
    category: 'collectible',
    rarity: 'uncommon',
    buyPrice: 2000,
    sellPrice: 1800,
    buyable: true,
    sellable: true,
  },
  diamond: {
    itemId: 'diamond',
    name: 'Diamond',
    emoji: '💎',
    description: 'A flawless diamond. Worth a fortune.',
    category: 'collectible',
    rarity: 'rare',
    buyPrice: 10000,
    sellPrice: 9500,
    buyable: true,
    sellable: true,
  },
  crown_jewel: {
    itemId: 'crown_jewel',
    name: 'Crown Jewel',
    emoji: '👑',
    description: 'An incredibly rare jewel fit for royalty.',
    category: 'collectible',
    rarity: 'epic',
    buyPrice: 50000,
    sellPrice: 48000,
    buyable: false,
    sellable: true,
  },
  star_fragment: {
    itemId: 'star_fragment',
    name: 'Star Fragment',
    emoji: '⭐',
    description: 'A fragment from a fallen star. Extremely rare.',
    category: 'collectible',
    rarity: 'legendary',
    buyPrice: 100000,
    sellPrice: 95000,
    buyable: false,
    sellable: true,
  },
  moon_stone: {
    itemId: 'moon_stone',
    name: 'Moon Stone',
    emoji: '🌙',
    description: 'A mythic stone from the moon. Almost priceless.',
    category: 'collectible',
    rarity: 'mythic',
    buyPrice: 500000,
    sellPrice: 480000,
    buyable: false,
    sellable: true,
  },

  // ── LOOT BOXES ─────────────────────────────────────────────────────────
  common_box: {
    itemId: 'common_box',
    name: 'Common Box',
    emoji: '📦',
    description: 'Contains random common items and some cash.',
    category: 'lootbox',
    rarity: 'common',
    buyPrice: 1000,
    sellPrice: 200,
    buyable: true,
    sellable: false,
    usable: true,
    effect: 'lootbox_common',
  },
  rare_box: {
    itemId: 'rare_box',
    name: 'Rare Box',
    emoji: '🟦',
    description: 'Contains rare items and decent cash.',
    category: 'lootbox',
    rarity: 'rare',
    buyPrice: 5000,
    sellPrice: 1000,
    buyable: true,
    sellable: false,
    usable: true,
    effect: 'lootbox_rare',
  },
  epic_box: {
    itemId: 'epic_box',
    name: 'Epic Box',
    emoji: '🟣',
    description: 'Contains epic items and big cash rewards.',
    category: 'lootbox',
    rarity: 'epic',
    buyPrice: 20000,
    sellPrice: 5000,
    buyable: true,
    sellable: false,
    usable: true,
    effect: 'lootbox_epic',
  },
  legendary_box: {
    itemId: 'legendary_box',
    name: 'Legendary Box',
    emoji: '🌟',
    description: 'Contains legendary items and massive cash.',
    category: 'lootbox',
    rarity: 'legendary',
    buyPrice: 100000,
    sellPrice: 20000,
    buyable: true,
    sellable: false,
    usable: true,
    effect: 'lootbox_legendary',
  },
  cursed_box: {
    itemId: 'cursed_box',
    name: 'Cursed Box',
    emoji: '💀',
    description: 'Could be amazing or absolutely terrible. Risk it!',
    category: 'lootbox',
    rarity: 'uncommon',
    buyPrice: 500,
    sellPrice: 100,
    buyable: true,
    sellable: false,
    usable: true,
    effect: 'lootbox_cursed',
  },

  // ── MATERIALS ──────────────────────────────────────────────────────────
  wood: {
    itemId: 'wood',
    name: 'Wood',
    emoji: '🪵',
    description: 'Chopped wood. Used for crafting.',
    category: 'material',
    rarity: 'common',
    buyPrice: 0,
    sellPrice: 50,
    buyable: false,
    sellable: true,
  },
  fish: {
    itemId: 'fish',
    name: 'Fish',
    emoji: '🐟',
    description: 'A fresh catch. Sell it or use it for crafting.',
    category: 'material',
    rarity: 'common',
    buyPrice: 0,
    sellPrice: 200,
    buyable: false,
    sellable: true,
  },
  rare_fish: {
    itemId: 'rare_fish',
    name: 'Rare Fish',
    emoji: '🐠',
    description: 'An exotic fish worth a lot of money.',
    category: 'material',
    rarity: 'rare',
    buyPrice: 0,
    sellPrice: 2000,
    buyable: false,
    sellable: true,
  },
  legendary_fish: {
    itemId: 'legendary_fish',
    name: 'Legendary Fish',
    emoji: '🦈',
    description: 'An incredibly rare catch. Sell for massive profit!',
    category: 'material',
    rarity: 'legendary',
    buyPrice: 0,
    sellPrice: 20000,
    buyable: false,
    sellable: true,
  },
  deer_hide: {
    itemId: 'deer_hide',
    name: 'Deer Hide',
    emoji: '🦌',
    description: 'Hide from a hunted deer. Used for crafting.',
    category: 'material',
    rarity: 'common',
    buyPrice: 0,
    sellPrice: 300,
    buyable: false,
    sellable: true,
  },
  bear_pelt: {
    itemId: 'bear_pelt',
    name: 'Bear Pelt',
    emoji: '🐻',
    description: 'A thick bear pelt. Worth good money.',
    category: 'material',
    rarity: 'rare',
    buyPrice: 0,
    sellPrice: 3000,
    buyable: false,
    sellable: true,
  },
  gear: {
    itemId: 'gear',
    name: 'Gear',
    emoji: '⚙️',
    description: 'A mechanical gear found while digging.',
    category: 'material',
    rarity: 'common',
    buyPrice: 0,
    sellPrice: 100,
    buyable: false,
    sellable: true,
  },
  battery: {
    itemId: 'battery',
    name: 'Battery',
    emoji: '🔋',
    description: 'A power cell found while digging.',
    category: 'material',
    rarity: 'uncommon',
    buyPrice: 0,
    sellPrice: 250,
    buyable: false,
    sellable: true,
  },
  thread: {
    itemId: 'thread',
    name: 'Thread',
    emoji: '🧵',
    description: 'Useful thread for crafting clothing.',
    category: 'material',
    rarity: 'common',
    buyPrice: 0,
    sellPrice: 80,
    buyable: false,
    sellable: true,
  },

  // ── PROPERTY ITEMS ─────────────────────────────────────────────────────
  renovation_kit: {
    itemId: 'renovation_kit',
    name: 'Renovation Kit',
    emoji: '🪟',
    description: '+10% property value permanently!',
    category: 'property',
    rarity: 'uncommon',
    buyPrice: 5000,
    sellPrice: 1500,
    buyable: true,
    sellable: true,
    usable: true,
    effect: 'property_value',
    effectValue: 1.1,
  },
  billboard: {
    itemId: 'billboard',
    name: 'Billboard',
    emoji: '📢',
    description: '+20% business income for 24 hours!',
    category: 'property',
    rarity: 'uncommon',
    buyPrice: 8000,
    sellPrice: 2500,
    buyable: true,
    sellable: true,
    usable: true,
    effect: 'business_boost',
    effectValue: 1.2,
    effectDuration: 24 * 60 * 60 * 1000,
  },
  master_key: {
    itemId: 'master_key',
    name: 'Master Key',
    emoji: '🔑',
    description: 'Collect all your properties at once instantly!',
    category: 'property',
    rarity: 'rare',
    buyPrice: 20000,
    sellPrice: 7000,
    buyable: true,
    sellable: true,
    usable: true,
    effect: 'collect_all_properties',
  },

  // ── SPECIAL / BLACK MARKET ─────────────────────────────────────────────
  insider_info: {
    itemId: 'insider_info',
    name: 'Insider Info',
    emoji: '🕵️',
    description: 'See the next 3 price movements for any asset!',
    category: 'special',
    rarity: 'epic',
    buyPrice: 0,
    sellPrice: 20000,
    buyable: false,
    sellable: true,
    usable: true,
    effect: 'market_insider',
  },
  market_bomb: {
    itemId: 'market_bomb',
    name: 'Market Bomb',
    emoji: '💣',
    description: 'Crash any asset by 10% instantly!',
    category: 'special',
    rarity: 'epic',
    buyPrice: 0,
    sellPrice: 40000,
    buyable: false,
    sellable: true,
    usable: true,
    effect: 'crash_asset',
    effectValue: 0.1,
  },
  pump_kit: {
    itemId: 'pump_kit',
    name: 'Pump Kit',
    emoji: '🚀',
    description: 'Pump any asset by 10% instantly!',
    category: 'special',
    rarity: 'epic',
    buyPrice: 0,
    sellPrice: 40000,
    buyable: false,
    sellable: true,
    usable: true,
    effect: 'pump_asset',
    effectValue: 0.1,
  },
  ghost_mode: {
    itemId: 'ghost_mode',
    name: 'Ghost Mode',
    emoji: '👻',
    description: 'Hidden from all leaderboards for 24 hours!',
    category: 'special',
    rarity: 'rare',
    buyPrice: 0,
    sellPrice: 30000,
    buyable: false,
    sellable: true,
    usable: true,
    effect: 'invisible',
    effectDuration: 24 * 60 * 60 * 1000,
  },
  money_printer: {
    itemId: 'money_printer',
    name: 'Money Printer',
    emoji: '💰',
    description: 'Generate $50,000 instantly!',
    category: 'special',
    rarity: 'legendary',
    buyPrice: 0,
    sellPrice: 200000,
    buyable: false,
    sellable: true,
    usable: true,
    effect: 'print_money',
    effectValue: 50000,
  },
};

// Loot box drop tables
const LOOT_TABLES = {
  common: {
    cash: { min: 500, max: 2000 },
    items: ['stone', 'copper', 'wood', 'fish', 'gear', 'thread', 'energy_drink'],
    weights: [30, 25, 20, 10, 8, 5, 2],
  },
  rare: {
    cash: { min: 2000, max: 10000 },
    items: ['silver_bar', 'gold_bar', 'rare_fish', 'deer_hide', 'battery', 'xp_booster', 'pro_bait', 'sharpshooter'],
    weights: [25, 20, 15, 15, 10, 8, 5, 2],
  },
  epic: {
    cash: { min: 10000, max: 50000 },
    items: ['diamond', 'bear_pelt', 'gold_magnet', 'casino_chip', 'tax_shield', 'mega_fertilizer', 'renovation_kit', 'billboard'],
    weights: [20, 15, 15, 12, 10, 10, 10, 8],
  },
  legendary: {
    cash: { min: 50000, max: 200000 },
    items: ['crown_jewel', 'star_fragment', 'vip_card', 'master_key', 'insider_info', 'pump_kit', 'market_bomb', 'moon_stone'],
    weights: [20, 15, 15, 15, 12, 10, 8, 5],
  },
  cursed: {
    cash: { min: -50000, max: 100000 },
    items: ['stone', 'moon_stone', 'money_printer', 'gear', 'cursed_box'],
    weights: [40, 5, 3, 40, 12],
  },
};

// Crafting recipes
const RECIPES = {
  bread: {
    name: '🍞 Bread',
    materials: { wheat: 5 },
    result: { itemId: 'bread', quantity: 1 },
    sellPrice: 500,
  },
  chair: {
    name: '🪑 Chair',
    materials: { wood: 3 },
    result: { itemId: 'chair', quantity: 1 },
    sellPrice: 1000,
  },
  guitar: {
    name: '🎸 Guitar',
    materials: { wood: 5, thread: 3 },
    result: { itemId: 'guitar', quantity: 1 },
    sellPrice: 8000,
  },
  machine: {
    name: '⚙️ Machine',
    materials: { gear: 10, battery: 5 },
    result: { itemId: 'machine', quantity: 1 },
    sellPrice: 25000,
  },
  robot: {
    name: '🤖 Robot',
    materials: { machine: 3, battery: 10 },
    result: { itemId: 'robot', quantity: 1 },
    sellPrice: 100000,
  },
  potion: {
    name: '🧪 Potion',
    materials: { fish: 3, thread: 2 },
    result: { itemId: 'xp_booster', quantity: 1 },
    sellPrice: 0,
  },
  sword: {
    name: '🗡️ Sword',
    materials: { gear: 5, deer_hide: 3 },
    result: { itemId: 'sharpshooter', quantity: 3 },
    sellPrice: 0,
  },
};

function getItem(itemId) {
  return ITEMS[itemId] || null;
}

function getAllItems() {
  return Object.values(ITEMS);
}

function getBuyableItems() {
  return Object.values(ITEMS).filter((i) => i.buyable && i.active !== false);
}

function rollLootBox(tier) {
  const table = LOOT_TABLES[tier];
  if (!table) return null;

  const totalWeight = table.weights.reduce((a, b) => a + b, 0);
  let r = Math.random() * totalWeight;
  let itemId = table.items[0];

  for (let i = 0; i < table.items.length; i++) {
    r -= table.weights[i];
    if (r <= 0) { itemId = table.items[i]; break; }
  }

  const cashAmount = Math.floor(
    Math.random() * (table.cash.max - table.cash.min) + table.cash.min
  );

  return { itemId, cashAmount };
}

const RARITY_COLORS = {
  common: '⬜',
  uncommon: '🟩',
  rare: '🟦',
  epic: '🟪',
  legendary: '🟨',
  mythic: '🔴',
};

module.exports = { ITEMS, RECIPES, LOOT_TABLES, getItem, getAllItems, getBuyableItems, rollLootBox, RARITY_COLORS };